FROM node:18

WORKDIR /app

# Install dependencies separately for caching
COPY package.json package-lock.json ./
RUN npm install


# Copy the source code
COPY . .

# Expose port
EXPOSE 3000

# Enable hot reload inside Docker
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "start"]
